baseURL = "https://azhou35.github.io/my-digital-garden/"
languageCode = "en-us"
googleAnalytics = "G-XYFD95KB4J"
relativeURLs = false
disablePathToLower = true
ignoreFiles = [
    "/content/templates/*",
    "/content/private/*",
    # Personal/system folders - not published
    "/content/my-vault/Dashboards/*",
    "/content/my-vault/Templates/*",
    "/content/my-vault/00 Inbox/*",
    "/content/my-vault/10 Library/*",
    "/content/my-vault/Readwise/*",
    "/content/my-vault/Clippings/*",
    "/content/my-vault/Excalidraw/*",
    "/content/my-vault/Markwhen/*",
    "/content/my-vault/kalshi/*",
    "/content/my-vault/substack drafts/*",
    "/content/my-vault/docs/*",
    "/content/my-vault/social ideas/*",
    "/content/my-vault/creative side hustle/*",
    "/content/my-vault/quartz/*",
]
summaryLength = 20
[pagination]
  pagerSize = 10
enableGitInfo = true

[markup]
    [markup.tableOfContents]
        endLevel = 3
        ordered = true
        startLevel = 2
    [markup.highlight]
        noClasses = false
        anchorLineNos = false
        codeFences = true
        guessSyntax = true
        hl_Lines = ""
        lineAnchors = ""
        lineNoStart = 1
        lineNos = true
        lineNumbersInTable = true
        style = "dracula"
    [frontmatter]
        lastmod = ["lastmod", ":git", "date", "publishDate"]
        publishDate = ["publishDate", "date"]
    [markup.goldmark.renderer]
        unsafe = true
